svc_enc_fuzzer: Add algorithm header for C++23
C++23 removed transitive includes so you need to add C++23 headers
directly to use its classes and functions. svc_enc_fuzzer needs the
algorithm header to use std::fill. I tested it in Android by building `m
svc_enc_fuzzer`.

Error:
external/libavc/fuzzer/svc_enc_fuzzer.cpp:347:5: error: no member named
'fill' in namespace 'std'; did you mean 'kill'?
  347 |     std::fill(mMemRecBufs.begin(), mMemRecBufs.end(), nullptr);
external/libavc/fuzzer/svc_enc_fuzzer.cpp:379:5: error: no member named
'fill' in namespace 'std'; did you mean 'kill'?
  379 |     std::fill(mMemRecBufs.begin(), mMemRecBufs.end(), nullptr);
external/libavc/fuzzer/svc_enc_fuzzer.cpp:1203:13: error: no member
named 'fill' in namespace 'std'; did you mean 'kill'?
 1203 |             std::fill(std::next(mEncBufs.mInputBuf.begin(),
bytesLeft), mEncBufs.mInputBuf.end(),